# Generated by Django 5.2.7 on 2025-10-21 03:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coletor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'coletor',
            },
        ),
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'cooperativa',
            },
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'produtor',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoColeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio_coleta', models.DateField()),
                ('data_fim_coleta', models.DateField()),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ACEITA', 'Aceita'), ('CANCELADA', 'Cancelada'), ('CONFIRMADA', 'Confirmada')], default='SOLICITADA', max_length=20)),
                ('coletor', models.ForeignKey(blank=True, db_column='coletor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas', to='aplicativo_web.coletor')),
                ('produtor', models.ForeignKey(db_column='produtor_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='aplicativo_web.produtor')),
            ],
            options={
                'db_table': 'solicitacao_coleta',
            },
        ),
    ]
