# Generated by Django 5.2.7 on 2025-11-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='status',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ACEITA', 'Aceita'), ('CANCELADA', 'Cancelada'), ('CONFIRMADA', 'Confirmada')], default='SOLICITADA', max_length=50),
        ),
    ]
