# Generated by Django 5.2.7 on 2025-10-21 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocoleta',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='coletor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas', to='aplicativo_web.coletor'),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='produtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='aplicativo_web.produtor'),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='status',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ACEITA', 'Aceita'), ('CANCELADA', 'Cancelada'), ('CONFIRMADA', 'Confirmada'), ('COLETADO', 'Coletado'), ('EM ROTA', 'Em Rota'), ('AGUARDANDO COLETOR', 'Aguardando Coletor')], default='SOLICITADA', max_length=20),
        ),
        migrations.AlterModelTable(
            name='solicitacaocoleta',
            table=None,
        ),
        migrations.CreateModel(
            name='ItemColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('PLASTICO', 'Plástico'), ('PAPEL', 'Papel'), ('VIDRO', 'Vidro'), ('METAL', 'Metal'), ('ORGANICO', 'Orgânico'), ('ELETRONICO', 'Eletrônico'), ('OUTRO', 'Outro')], max_length=50)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='aplicativo_web.solicitacaocoleta')),
            ],
        ),
    ]
