# Generated by Django 5.2.7 on 2025-11-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_web', '0002_alter_solicitacaocoleta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='status',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ACEITA', 'Aceita'), ('CANCELADA', 'Cancelada'), ('CONFIRMADA', 'Confirmada'), ('AGUARDANDO', 'aguardando')], default='SOLICITADA', max_length=55),
        ),
    ]
