# Generated by Django 5.2.6 on 2025-10-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_web', '0002_solicitacaocoleta_observacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaocoleta',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='solicitacaocoleta',
            name='data_fim_coleta',
        ),
        migrations.RemoveField(
            model_name='solicitacaocoleta',
            name='data_inicio_coleta',
        ),
        migrations.RemoveField(
            model_name='solicitacaocoleta',
            name='horario_fim',
        ),
        migrations.RemoveField(
            model_name='solicitacaocoleta',
            name='horario_inicio',
        ),
        migrations.RemoveField(
            model_name='solicitacaocoleta',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='solicitacaocoleta',
            name='fim_coleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaocoleta',
            name='inicio_coleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='status',
            field=models.CharField(default='SOLICITADA', max_length=20),
        ),
        migrations.AlterModelTable(
            name='solicitacaocoleta',
            table='solicitacao_coleta',
        ),
    ]
