# Generated by Django 5.2.7 on 2025-10-22 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_web', '0003_remove_solicitacaocoleta_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaocoleta',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='itemcoleta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='itemcoleta',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='itemcoleta',
            name='id',
        ),
        migrations.AddField(
            model_name='itemcoleta',
            name='id_item',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='itemcoleta',
            name='nome_residuo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcoleta',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaocoleta',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coletor',
            name='cpf',
            field=models.CharField(db_column='cpf_cnpj', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='itemcoleta',
            name='solicitacao',
            field=models.ForeignKey(db_column='id_solicitacao', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='aplicativo_web.solicitacaocoleta'),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='coletor',
            field=models.ForeignKey(blank=True, db_column='coletor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas', to='aplicativo_web.coletor'),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='fim_coleta',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='inicio_coleta',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='produtor',
            field=models.ForeignKey(db_column='produtor_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='aplicativo_web.produtor'),
        ),
        migrations.AlterField(
            model_name='solicitacaocoleta',
            name='status',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('ACEITA', 'Aceita'), ('CANCELADA', 'Cancelada'), ('CONFIRMADA', 'Confirmada'), ('COLETADO', 'Coletado'), ('EM ROTA', 'Em Rota'), ('AGUARDANDO COLETOR', 'Aguardando Coletor')], default='SOLICITADA', max_length=20),
        ),
        migrations.AlterModelTable(
            name='itemcoleta',
            table='item_solicitacao',
        ),
    ]
