# Generated by Django 5.2.6 on 2025-10-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_web', '0004_alter_solicitacaocoleta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coletor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='cpf',
            field=models.CharField(db_column='cpf_cnpj', max_length=18, unique=True),
        ),
    ]
