# Generated by Django 5.2.7 on 2025-11-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_web', '0005_alter_coletor_cpf_alter_produtor_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coletor',
            name='cpf',
            field=models.CharField(db_column='cpf_cnpj', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
